services:
  cloudstreamweb:
    build:
      context: .
      target: production
    container_name: cloudstreamweb
    x-casaos:
      author: user
      category: Video
      icon: https://cdn-icons-png.flaticon.com/512/864/864434.png
      title: CloudStream Web
      description: Versão Web do CloudStream - Plataforma de streaming baseada em plugins.
    ports:
      - "8085:8085"
    volumes:
      - ./server/data:/app/server/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=8085
      # Adicione outras variáveis de ambiente aqui (.env)
